// Plan types
export type PlanType = 'free' | 'trial' | 'starter' | 'pro';
export type SubscriptionStatus = 'free' | 'trial' | 'active' | 'past_due' | 'canceled' | 'paused';

// User
export interface User {
  id: string;
  email: string;
  name: string | null;
  image: string | null;
  youtube_channel_id: string | null;
  youtube_access_token: string | null;
  youtube_refresh_token: string | null;
  token_expires_at: string | null;
  niche_id: string | null;
  niche_detected_at: string | null;
  subscription_status: SubscriptionStatus;
  stripe_customer_id: string | null;
  stripe_subscription_id: string | null;
  trial_ends_at: string | null;
  onboarding_completed: boolean;
  created_at: string;
  updated_at: string;
}

// Channel snapshot (user's own data, stored daily)
export interface ChannelSnapshot {
  id: string;
  user_id: string;
  snapshot_date: string;
  subscriber_count: number | null;
  total_views: number | null;
  videos_count: number | null;
  avg_views_per_video: number | null;
  avg_ctr: number | null;
  avg_view_duration_seconds: number | null;
  avg_like_ratio: number | null;
  estimated_monthly_revenue: number | null;
  rpm: number | null;
  momentum_score: number | null;
  created_at: string;
}

// Video (user's own videos with full analytics)
export interface Video {
  id: string;
  user_id: string;
  youtube_video_id: string;
  title: string | null;
  published_at: string | null;
  duration_seconds: number | null;
  view_count: number | null;
  like_count: number | null;
  comment_count: number | null;
  share_count: number | null;
  save_count: number | null;
  ctr: number | null;
  avg_view_duration_seconds: number | null;
  retention_percentage: number | null;
  impressions: number | null;
  traffic_source_search: number | null;
  traffic_source_suggested: number | null;
  traffic_source_browse: number | null;
  traffic_source_external: number | null;
  subscriber_gain: number | null;
  revenue_estimate: number | null;
  rpm: number | null;
  thumbnail_url: string | null;
  performance_score: number | null;
  synced_at: string;
}

// Competitor (channels tracked for each user)
export interface Competitor {
  id: string;
  user_id: string;
  youtube_channel_id: string;
  channel_name: string | null;
  channel_thumbnail: string | null;
  subscriber_count: number | null;
  total_views: number | null;
  tier: 1 | 2 | 3; // 1 = similar, 2 = aspirational, 3 = dominator
  is_auto_detected: boolean;
  is_active: boolean;
  last_synced_at: string | null;
  created_at: string;
}

// Competitor video (public data only)
export interface CompetitorVideo {
  id: string;
  competitor_id: string;
  youtube_video_id: string;
  title: string | null;
  published_at: string | null;
  view_count: number | null;
  like_count: number | null;
  comment_count: number | null;
  duration_seconds: number | null;
  thumbnail_url: string | null;
  velocity_score: number | null; // views per hour in first 48hrs
  performance_vs_avg: number | null; // ratio vs that channel's average
  is_viral: boolean;
  synced_at: string;
}

// Gap score (calculated weekly)
export interface GapScore {
  id: string;
  user_id: string;
  calculated_at: string;
  overall_score: number; // 0-100, higher = bigger gap = more opportunity
  views_gap_score: number;
  ctr_gap_score: number;
  upload_frequency_gap_score: number;
  watch_time_gap_score: number;
  topic_coverage_gap_score: number;
  estimated_revenue_gap: number; // monthly dollars left on table
  primary_bottleneck: string; // which gap costs the most money
}

// Digest (Claude-generated weekly report)
export interface Digest {
  id: string;
  user_id: string;
  week_start_date: string;
  content: string; // full Claude-generated text
  video_ideas: VideoIdea[] | null;
  key_metrics: Record<string, unknown> | null;
  email_sent_at: string | null;
  opened_at: string | null;
  created_at: string;
}

// Trend (viral video detected in niche)
export interface Trend {
  id: string;
  user_id: string;
  competitor_id: string | null;
  youtube_video_id: string | null;
  title: string | null;
  channel_name: string | null;
  view_count: number | null;
  velocity_score: number | null;
  detected_at: string;
  alert_sent: boolean;
}

// User settings
export interface UserSettings {
  user_id: string;
  weekly_digest_enabled: boolean;
  alerts_enabled: boolean;
  alert_threshold_multiplier: number;
  digest_day: string;
  timezone: string;
  updated_at: string;
}

// Video idea (generated by Claude, stored in digest.video_ideas)
export interface VideoIdea {
  title: string;
  opportunityScore: number;
  reason: string;
  suggestedLength: string;
  thumbnailApproach: string;
  hookDataPoint: string;
}
